apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z0mhds5lm-python 
  janus-idp.io/tekton: z0mhds5lm-python
  backstage.io/kubernetes-id: z0mhds5lm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z0mhds5lm-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml